name: Publish

on: create

jobs:
  build_and_publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: publishPlugin
      env:
        ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.PluginUploadToken }}
